export type HrScoutCandidate = {
  availability: "Aktif arayışta" | "Görüşmeye açık" | "Pasif aday";
  category:
    | "Mühendislik"
    | "Ürün & Tasarım"
    | "Satış"
    | "Veri"
    | "İnsan Kaynakları"
    | "Pazarlama";
  company: string;
  experienceYears: number;
  id: string;
  initials: string;
  location: string;
  matchScore: number;
  name: string;
  role: string;
  skills: readonly string[];
  source: string;
  workModel: "Hibrit" | "Ofis" | "Uzaktan";
};

export const hrScoutCandidates = [
  {
    id: "scout-101",
    name: "Derya Acar",
    initials: "DA",
    role: "Kıdemli Full Stack Geliştirici",
    company: "Flowly",
    category: "Mühendislik",
    experienceYears: 8,
    location: "İstanbul",
    workModel: "Hibrit",
    availability: "Görüşmeye açık",
    matchScore: 96,
    source: "Teknoloji topluluğu",
    skills: ["React", "Node.js", "PostgreSQL"],
  },
  {
    id: "scout-102",
    name: "Kaan Tekin",
    initials: "KT",
    role: "Senior Data Scientist",
    company: "Trendbox",
    category: "Veri",
    experienceYears: 7,
    location: "Ankara",
    workModel: "Uzaktan",
    availability: "Görüşmeye açık",
    matchScore: 94,
    source: "AI yetenek ağı",
    skills: ["Python", "LLM", "MLOps"],
  },
  {
    id: "scout-103",
    name: "Lara Yıldız",
    initials: "LY",
    role: "Ürün Tasarımcısı",
    company: "MobiLab",
    category: "Ürün & Tasarım",
    experienceYears: 5,
    location: "İzmir",
    workModel: "Uzaktan",
    availability: "Aktif arayışta",
    matchScore: 92,
    source: "Tasarım topluluğu",
    skills: ["Figma", "UX Research", "Design System"],
  },
  {
    id: "scout-104",
    name: "Oğuzhan Eren",
    initials: "OE",
    role: "Enterprise Account Executive",
    company: "Cloudify",
    category: "Satış",
    experienceYears: 9,
    location: "İstanbul",
    workModel: "Hibrit",
    availability: "Pasif aday",
    matchScore: 91,
    source: "Sektör ağı",
    skills: ["B2B SaaS", "CRM", "Enterprise"],
  },
  {
    id: "scout-105",
    name: "Melis Güneş",
    initials: "MG",
    role: "Talent Acquisition Partner",
    company: "NovaWorks",
    category: "İnsan Kaynakları",
    experienceYears: 6,
    location: "İstanbul",
    workModel: "Hibrit",
    availability: "Aktif arayışta",
    matchScore: 89,
    source: "İK topluluğu",
    skills: ["Tech Hiring", "Sourcing", "Employer Brand"],
  },
  {
    id: "scout-106",
    name: "Bora Kaya",
    initials: "BK",
    role: "DevOps Mühendisi",
    company: "Stackline",
    category: "Mühendislik",
    experienceYears: 6,
    location: "Bursa",
    workModel: "Uzaktan",
    availability: "Görüşmeye açık",
    matchScore: 88,
    source: "Açık kaynak topluluğu",
    skills: ["Kubernetes", "AWS", "Terraform"],
  },
  {
    id: "scout-107",
    name: "Ece Arslan",
    initials: "EA",
    role: "Kıdemli Ürün Yöneticisi",
    company: "Paylink",
    category: "Ürün & Tasarım",
    experienceYears: 8,
    location: "İstanbul",
    workModel: "Hibrit",
    availability: "Pasif aday",
    matchScore: 87,
    source: "Fintech ağı",
    skills: ["Product Strategy", "Fintech", "Analytics"],
  },
  {
    id: "scout-108",
    name: "Cem Sönmez",
    initials: "CS",
    role: "Frontend Geliştirici",
    company: "Piksel",
    category: "Mühendislik",
    experienceYears: 4,
    location: "Eskişehir",
    workModel: "Uzaktan",
    availability: "Aktif arayışta",
    matchScore: 86,
    source: "Geliştirici topluluğu",
    skills: ["React", "TypeScript", "Next.js"],
  },
  {
    id: "scout-109",
    name: "Zeynep Bulut",
    initials: "ZB",
    role: "Growth Marketing Manager",
    company: "Sepetim",
    category: "Pazarlama",
    experienceYears: 7,
    location: "İstanbul",
    workModel: "Ofis",
    availability: "Görüşmeye açık",
    matchScore: 85,
    source: "Pazarlama ağı",
    skills: ["Growth", "Performance", "CRM"],
  },
  {
    id: "scout-110",
    name: "Arda Şahin",
    initials: "AŞ",
    role: "Mobil Uygulama Geliştirici",
    company: "RouteGo",
    category: "Mühendislik",
    experienceYears: 5,
    location: "Ankara",
    workModel: "Hibrit",
    availability: "Aktif arayışta",
    matchScore: 84,
    source: "Mobil geliştirici ağı",
    skills: ["Flutter", "Dart", "Firebase"],
  },
  {
    id: "scout-111",
    name: "Nil Aksoy",
    initials: "NA",
    role: "İş Zekâsı Analisti",
    company: "MetricLab",
    category: "Veri",
    experienceYears: 3,
    location: "İzmir",
    workModel: "Hibrit",
    availability: "Görüşmeye açık",
    matchScore: 82,
    source: "Veri topluluğu",
    skills: ["SQL", "Power BI", "dbt"],
  },
  {
    id: "scout-112",
    name: "Onur Demir",
    initials: "OD",
    role: "UX Araştırmacısı",
    company: "Humanly",
    category: "Ürün & Tasarım",
    experienceYears: 4,
    location: "İstanbul",
    workModel: "Uzaktan",
    availability: "Pasif aday",
    matchScore: 81,
    source: "Araştırma topluluğu",
    skills: ["User Research", "Testing", "Journey Map"],
  },
  {
    id: "scout-113",
    name: "İrem Koç",
    initials: "İK",
    role: "İK İş Ortağı",
    company: "PeopleFirst",
    category: "İnsan Kaynakları",
    experienceYears: 7,
    location: "Kocaeli",
    workModel: "Hibrit",
    availability: "Aktif arayışta",
    matchScore: 80,
    source: "Referans",
    skills: ["HRBP", "Talent Management", "OKR"],
  },
  {
    id: "scout-114",
    name: "Deniz Korkmaz",
    initials: "DK",
    role: "Sales Development Lead",
    company: "ReachUp",
    category: "Satış",
    experienceYears: 5,
    location: "Ankara",
    workModel: "Ofis",
    availability: "Görüşmeye açık",
    matchScore: 79,
    source: "Satış topluluğu",
    skills: ["Outbound", "Salesforce", "Team Lead"],
  },
  {
    id: "scout-115",
    name: "Selin Ergin",
    initials: "SE",
    role: "Backend Geliştirici",
    company: "CoreBase",
    category: "Mühendislik",
    experienceYears: 3,
    location: "İstanbul",
    workModel: "Hibrit",
    availability: "Aktif arayışta",
    matchScore: 78,
    source: "Geliştirici topluluğu",
    skills: [".NET", "C#", "Azure"],
  },
] satisfies readonly HrScoutCandidate[];
