export {
  candidates,
  departmentMetrics,
  funnelStages,
  hrDashboardStats,
  hrFaqs,
  hrNavigationItems,
  hrPriorities,
  hrProfile,
  hrUtilityItems,
  interviews,
  monthlyHiring,
  requisitions,
  type HrNavigationKey,
  type HrRequisition,
  type HrUtilityKey,
} from "./hr-dashboard-data";
