export const ROUTES = {
  home: "/",
  landing: "/",
  login: "/login",
  register: "/register",
  candidate: "/candidate",
  candidateApplications: "/candidate/applications",
  candidateHelpCenter: "/candidate/help-center",
  candidateSettings: "/candidate/settings",
  employer: "/employer",
  employerHelpCenter: '/employer/help-center',
  employerJobs: "/employer/jobs",
  employerApplications: "/employer/applications",
  employerTalents: "/employer/talents",
  employerSettings: "/employer/settings",
  hr: "/hr",
  hrRequisitions: "/hr/requisitions",
  hrCandidates: "/hr/candidates",
  hrInterviews: "/hr/interviews",
  hrReports: "/hr/reports",
  hrHelpCenter: "/hr/help-center",
  hrSettings: "/hr/settings",
  myCandidate: "/mycandidate",
  resumeUpload: "/resume-upload",
  jobs: "/jobs",
  newJob: "/jobs/new",
  talentBenchmarking: "/talent-benchmarking",
  assessment: "/assessment",
  assessmentSession: "/assessment/session",
} as const;

