export const ROUTES = {
  home: "/",
  landing: "/",
  login: "/login",
  register: "/register",
  candidate: "/candidate",
  candidateHelpCenter: "/candidate/help-center",
  employer: "/employer",
  employerHelpCenter: '/employer/help-center',
  employerJobs: "/employer/jobs",
  employerApplications: "/employer/applications",
  employerTalents: "/employer/talents",
  employerSettings: "/employer/settings",
  myCandidate: "/mycandidate",
  resumeUpload: "/resume-upload",
  jobs: "/jobs",
  newJob: "/jobs/new",
  talentBenchmarking: "/talent-benchmarking",
  assessment: "/assessment",
  assessmentSession: "/assessment/session",
} as const;

