import {
  MdAutorenew,
  MdLogout,
  MdOutlineAccountBalance,
  MdOutlineAdd,
  MdOutlineAddCircle,
  MdOutlineAnalytics,
  MdOutlineApartment,
  MdOutlineArrowBack,
  MdOutlineArrowDropDown,
  MdOutlineArrowForward,
  MdOutlineAssignment,
  MdOutlineAssignmentInd,
  MdOutlineAutoAwesome,
  MdOutlineBadge,
  MdOutlineBolt,
  MdOutlineBusiness,
  MdOutlineBusinessCenter,
  MdOutlineCalendarMonth,
  MdOutlineCampaign,
  MdOutlineCheck,
  MdOutlineCheckCircle,
  MdOutlineChevronLeft,
  MdOutlineChevronRight,
  MdOutlineClose,
  MdOutlineContactPage,
  MdOutlineCorporateFare,
  MdOutlineDarkMode,
  MdOutlineDashboard,
  MdOutlineDescription,
  MdOutlineDocumentScanner,
  MdOutlineDomain,
  MdOutlineDownload,
  MdOutlineEdit,
  MdOutlineEditNote,
  MdOutlineEventAvailable,
  MdOutlineExpandMore,
  MdOutlineForum,
  MdOutlineGroup,
  MdOutlineGroups,
  MdOutlineHandshake,
  MdOutlineHelp,
  MdOutlineHome,
  MdOutlineHub,
  MdOutlineLanguage,
  MdOutlineLightMode,
  MdOutlineLightbulb,
  MdOutlineListAlt,
  MdOutlineLocationOn,
  MdOutlineLock,
  MdOutlineMail,
  MdOutlineManageAccounts,
  MdOutlineMarkChatRead,
  MdOutlineMenu,
  MdOutlineMoreHoriz,
  MdOutlineNotifications,
  MdOutlineNotificationsActive,
  MdOutlinePerson,
  MdOutlinePersonAdd,
  MdOutlinePostAdd,
  MdOutlinePsychology,
  MdOutlineRadar,
  MdOutlineRecordVoiceOver,
  MdOutlineSchool,
  MdOutlineScience,
  MdOutlineSearch,
  MdOutlineSearchOff,
  MdOutlineSettings,
  MdOutlineShare,
  MdOutlineShowChart,
  MdOutlineSpaceDashboard,
  MdOutlineStorefront,
  MdOutlineSupportAgent,
  MdOutlineTrendingUp,
  MdOutlineTune,
  MdOutlineVerified,
  MdOutlineVisibility,
  MdOutlineVisibilityOff,
  MdOutlineWarning,
  MdOutlineWork,
  MdOutlineWorkHistory,
  MdOutlineWorkspacePremium,
  MdPerson,
} from "react-icons/md";
import { TbBinoculars } from "react-icons/tb";
import type { IconType } from "react-icons";

const icons: Record<string, IconType> = {
  account_balance: MdOutlineAccountBalance,
  add: MdOutlineAdd,
  add_circle: MdOutlineAddCircle,
  analytics: MdOutlineAnalytics,
  apartment: MdOutlineApartment,
  arrow_back: MdOutlineArrowBack,
  arrow_drop_down: MdOutlineArrowDropDown,
  arrow_forward: MdOutlineArrowForward,
  assignment: MdOutlineAssignment,
  assignment_add: MdOutlinePostAdd,
  assignment_ind: MdOutlineAssignmentInd,
  auto_awesome: MdOutlineAutoAwesome,
  badge: MdOutlineBadge,
  binoculars: TbBinoculars,
  bolt: MdOutlineBolt,
  business: MdOutlineBusiness,
  business_center: MdOutlineBusinessCenter,
  calendar_month: MdOutlineCalendarMonth,
  campaign: MdOutlineCampaign,
  check: MdOutlineCheck,
  check_circle: MdOutlineCheckCircle,
  checklist_edit: MdOutlineEditNote,
  chevron_left: MdOutlineChevronLeft,
  chevron_right: MdOutlineChevronRight,
  close: MdOutlineClose,
  contact_page: MdOutlineContactPage,
  corporate_fare: MdOutlineCorporateFare,
  dark_mode: MdOutlineDarkMode,
  dashboard: MdOutlineDashboard,
  description: MdOutlineDescription,
  document_scanner: MdOutlineDocumentScanner,
  domain: MdOutlineDomain,
  door_open: MdLogout,
  download: MdOutlineDownload,
  edit: MdOutlineEdit,
  event_available: MdOutlineEventAvailable,
  expand_more: MdOutlineExpandMore,
  forum: MdOutlineForum,
  group: MdOutlineGroup,
  groups: MdOutlineGroups,
  handshake: MdOutlineHandshake,
  help: MdOutlineHelp,
  home: MdOutlineHome,
  hub: MdOutlineHub,
  language: MdOutlineLanguage,
  light_mode: MdOutlineLightMode,
  lightbulb: MdOutlineLightbulb,
  list_alt: MdOutlineListAlt,
  location_on: MdOutlineLocationOn,
  lock: MdOutlineLock,
  mail: MdOutlineMail,
  menu: MdOutlineMenu,
  monitoring: MdOutlineShowChart,
  more_horiz: MdOutlineMoreHoriz,
  notifications: MdOutlineNotifications,
  notifications_active: MdOutlineNotificationsActive,
  person: MdOutlinePerson,
  person_add: MdOutlinePersonAdd,
  person_edit: MdOutlineManageAccounts,
  person_silhouette: MdPerson,
  progress_activity: MdAutorenew,
  psychology: MdOutlinePsychology,
  radar: MdOutlineRadar,
  record_voice_over: MdOutlineRecordVoiceOver,
  school: MdOutlineSchool,
  science: MdOutlineScience,
  search: MdOutlineSearch,
  search_off: MdOutlineSearchOff,
  settings: MdOutlineSettings,
  share: MdOutlineShare,
  space_dashboard: MdOutlineSpaceDashboard,
  storefront: MdOutlineStorefront,
  support_agent: MdOutlineSupportAgent,
  support_check: MdOutlineMarkChatRead,
  trending_up: MdOutlineTrendingUp,
  tune: MdOutlineTune,
  verified: MdOutlineVerified,
  visibility: MdOutlineVisibility,
  visibility_off: MdOutlineVisibilityOff,
  warning: MdOutlineWarning,
  work: MdOutlineWork,
  work_history: MdOutlineWorkHistory,
  workspace_premium: MdOutlineWorkspacePremium,
};

// Resolves icon names supplied by navigation and page data.
export function AppIcon({ children, className = "" }: { children: string; className?: string }) {
  const Icon = icons[children.trim()];
  if (!Icon) return null;
  return <Icon aria-hidden="true" focusable="false" className={`inline-block h-[1em] w-[1em] shrink-0 align-[-0.125em] ${className}`} />;
}
